server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 1234

  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: []
    password: []
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp